### ISSUE TITLE
Projects have cover images

### ISSUE THREAD

**Issue by dillondrenzek** [dillondrenzek/dillon-drenzek-com#100]
### Requirements
- Projects in a list should display a "cover image"

### Todo
In Sketch:
- [x] Get images for mock Project Entry
- [x] Design what Project Entry looks like
- [x] Update design for different screen sizes

Then:
- [ ] (#116) extend `Entry` with `block`s
- [ ] (#117) create `ProjectEntry` composing `Entry` and its accessory mixins
- [ ] (#114) remove skills on projects
